# Generated by Django 4.1.5 on 2023-05-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.CharField(max_length=255)),
                ('SSD', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('year', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('trash', models.BooleanField(default=False)),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_id', to='api.configurate')),
            ],
        ),
    ]
