# Generated by Django 4.1.5 on 2023-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='configure',
            field=models.JSONField(),
        ),
    ]
